version: '3.4'

services:
  backend:
    platform: linux/amd64
    image: jemokajack/batchalign-backend:0.2.40
    ports:
      - 8080:8080
  db:
    image: jemokajack/batchalign-db:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: batchalign
  frontend:
    image: jemokajack/batchalign-frontend:latest
    ports:
      - 80:4173



