version: '3.9'

services:
  db:
    image: jemokajack/batchalign-db:latest
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: batchalign
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=batchalign
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  backend:
    platform: linux/amd64
    image: jemokajack/batchalign-backend:0.2.40
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    expose:
      - 8080
    entrypoint: /bin/bash -c "mamba run -n batchalign batchalign daemon --db_user=root --db_password=batchalign --db_ip=db ./"
  frontend:
    image: jemokajack/batchalign-frontend:latest
    ports:
      - 80:4173



