version: '3.9'

services:
  db:
    image: jemokajack/batchalign-db:latest
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: batchalign
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=batchalign
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  backend:
    platform: linux/amd64
    image: jemokajack/batchalign-backend:0.3.1
    depends_on:
      db:
        condition: service_healthy
    dns:
      - 8.8.8.8
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:8080
    healthcheck:
      # no --fail because 404 is fine, and $$ apparently because docker needs escaping the $
      test: wget --no-verbose --spider -q "http://0.0.0.0:8080" || [ $$? -eq 8 ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 180
  frontend:
    image: jemokajack/batchalign-frontend:latest
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_healthy
    ports:
      - 4173:4173



