version: '3.49

services:
  db:
    image: jemokajack/batchalign-db:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: batchalign
  backend:
    platform: linux/amd64
    image: jemokajack/batchalign-backend:0.2.40
    depends_on:
      db:
        condition: service_completed_successfully
    ports:
      - 8080:8080
  frontend:
    image: jemokajack/batchalign-frontend:latest
    depends_on:
      backend:
        condition: service_completed_successfully
    ports:
      - 80:4173



